In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/Sample - Superstore.csv')

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 9994
Columns: 21

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06/12/2016,06/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [6]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
missing_summary = pd.DataFrame({
    'Column': df.columns,
    'Missing Values': df.isnull().sum().values
})

missing_summary

           Column  Missing Values
0          Row ID               0
1        Order ID               0
2      Order Date               0
3       Ship Date               0
4       Ship Mode               0
5     Customer ID               0
6   Customer Name               0
7         Segment               0
8         Country               0
9            City               0
10          State               0
11    Postal Code               0
12         Region               0
13     Product ID               0
14       Category               0
15   Sub-Category               0
16   Product Name               0
17          Sales               0
18       Quantity               0
19       Discount               0
20         Profit               0

In [8]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [9]:
print(df.dtypes)

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [10]:
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')

print("Invalid Order Dates:", df['Order Date'].isnull().sum())
print("Invalid Ship Dates:", df['Ship Date'].isnull().sum())

Invalid Order Dates: 0
Invalid Ship Dates: 0

In [11]:
invalid_shipping_dates = df[df['Ship Date'] < df['Order Date']]

print("Rows where Ship Date is before Order Date:",
      len(invalid_shipping_dates))

Rows where Ship Date is before Order Date: 0

In [12]:
invalid_quantity = df[df['Quantity'] <= 0]

print("Rows with invalid Quantity:", len(invalid_quantity))

Rows with invalid Quantity: 0

In [13]:
invalid_discount = df[
    (df['Discount'] < 0) | (df['Discount'] > 1)
]

print("Rows with invalid Discount:", len(invalid_discount))

Rows with invalid Discount: 0

In [14]:
invalid_sales = df[df['Sales'] <= 0]

print("Rows with invalid Sales:", len(invalid_sales))

Rows with invalid Sales: 0

In [15]:
df['Postal Code'] = df['Postal Code'].astype(str)

invalid_postal = df[
    df['Postal Code'].str.len() != 5
]

print("Postal codes not having 5 digits:",
      len(invalid_postal))

Postal codes not having 5 digits: 449

In [16]:
issue_log = pd.DataFrame({
    'Issue Type': [
        'Missing Values',
        'Duplicate Rows',
        'Invalid Order Dates',
        'Invalid Ship Dates',
        'Ship Date Before Order Date',
        'Invalid Quantity',
        'Invalid Discount',
        'Invalid Sales',
        'Postal Code Format'
    ],
    'Issue Count': [
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df['Order Date'].isnull().sum(),
        df['Ship Date'].isnull().sum(),
        len(invalid_shipping_dates),
        len(invalid_quantity),
        len(invalid_discount),
        len(invalid_sales),
        len(invalid_postal)
    ]
})

issue_log

                    Issue Type  Issue Count
0               Missing Values            0
1               Duplicate Rows            0
2          Invalid Order Dates            0
3           Invalid Ship Dates            0
4  Ship Date Before Order Date            0
5             Invalid Quantity            0
6             Invalid Discount            0
7                Invalid Sales            0
8           Postal Code Format          449

In [17]:
cleaned_df = df.copy()

cleaned_df['Postal Code'] = (
    cleaned_df['Postal Code']
    .astype(str)
    .str.zfill(5)
)

print("Original rows:", len(df))
print("Cleaned rows:", len(cleaned_df))

Original rows: 9994
Cleaned rows: 9994

In [18]:
cleaned_df.to_csv('/content/Superstore_Cleaned.csv', index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [19]:
issue_log.to_csv('/content/Superstore_Issue_Log.csv', index=False)

print("Issue log saved successfully!")

Issue log saved successfully!

In [20]:
print("Cleaned dataset rows:", len(cleaned_df))
print("Cleaned dataset columns:", len(cleaned_df.columns))
print("Issue log rows:", len(issue_log))

print("\nFiles created:")
print("1. Superstore_Cleaned.csv")
print("2. Superstore_Issue_Log.csv")

Cleaned dataset rows: 9994
Cleaned dataset columns: 21
Issue log rows: 9

Files created:
1. Superstore_Cleaned.csv
2. Superstore_Issue_Log.csv